#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(\
			LT(4,KC_TAB), KC_Q, KC_W, KC_E, KC_R, KC_T,        KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, \
			LCTL_T(KC_ESC), KC_A, KC_S, KC_D, KC_F, KC_G,      KC_H, KC_J, KC_K, KC_L, LT(3,KC_SCLN), MEH_T(KC_QUOT), \
			KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B,             KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_SLSH, \
		 	KC_LALT, LT(2,KC_LANG2), LGUI_T(KC_SPC),	   LT(1,KC_ENT), LT(2,KC_LANG1), LGUI(KC_SPC) \
			),

	[1] = LAYOUT(\
			KC_TAB, KC_LBRC, KC_RBRC, KC_LPRN, KC_RPRN, KC_GRV,		       KC_DEL, KC_7, KC_8, KC_9, KC_0, KC_BSLS, \
			LCTL_T(KC_ESC), KC_PSLS, KC_PAST, KC_MINS, KC_PPLS, KC_PEQL,           KC_BSPC, KC_4, KC_5, KC_6, KC_DOT, KC_NO, \
			KC_LSFT, KC_PERC, KC_CIRC, KC_LT, KC_GT, KC_GRV,                       LALT(KC_F), KC_1, KC_2, KC_3, KC_DOT, KC_NO, \
			KC_LALT, LT(2,KC_LANG2), LGUI_T(KC_SPC),			       KC_ENT, KC_0, KC_0 \
			),

	[2] = LAYOUT(\
			KC_TAB, LCTL(KC_F2), LCTL(KC_LEFT), LGUI(KC_TAB), LCTL(KC_RGHT), LCTL(KC_F8),			KC_HOME, KC_END, KC_PGUP, KC_PGDN, KC_NO, KC_BSPC, \
			LCTL_T(KC_ESC), LGUI(KC_LBRC), LCTL(KC_TAB), LALT(KC_TAB), LCTL(KC_TAB), LGUI(KC_RBRC),         KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_ENT,\
			KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 							KC_UNDS, KC_PLUS, KC_LBRC, KC_RBRC, KC_NO, KC_LSFT,\
			KC_LALT, KC_LANG2, LGUI_T(KC_SPC),								LT(1,KC_ENT), KC_LANG1, KC_TAB \
			),

	[3] = LAYOUT(\
			KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, HYPR(KC_F16), 			HYPR(KC_F17), KC_PGUP, KC_MS_U, KC_BTN2, KC_NO, KC_NO,\
			KC_NO, LGUI(KC_LBRC), KC_NO, KC_BTN2, KC_BTN1, LGUI(KC_RBRC), 		KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_NO, KC_NO, \
			KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, HYPR(KC_F18), 			HYPR(KC_F19), KC_PGDN, KC_NO, KC_NO, KC_NO, KC_NO,\
			LGUI_T(KC_LANG2), KC_ACL2, KC_ACL1,					KC_ACL2, KC_ACL0, KC_ACL1 \
			),

	[4] = LAYOUT(\
			KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 			KC_NO, KC_F14, KC_F15, KC_NO, KC_NO, KC_NO, \
			KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,			KC_MRWD, KC__VOLDOWN, KC__VOLUP, KC_MFFD, KC_NO, KC_NO, \
			KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,			KC_NO, KC__MUTE, KC_NO, KC_NO, KC_NO, KC_NO, \
			KC_NO, KC_NO, KC_NO, 						KC_NO, KC_NO, KC_NO \
			)

};
